$("<%= j(render partial: 'form_edit') %>").appendTo("#modal_empty")
Materialize.updateTextFields()
datepicker_init()
$('.modal-content input.datepicker').val("<%= date_ukr(@grain_input.date) %>")
$('select').material_select()
$('#modal_empty').modal('open')