default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ekomalt_development

test:
  <<: *default
  database: ekomalt_test

production:
  <<: *default
  database: ekomalt_production
  username: ekomalt
  password: <%= ENV['EKOMALT_DATABASE_PASSWORD'] %>
